services:
  bitcoind:
    image: registry.gitlab.com/hashbeam/docker/bitcoind:28.1
    command: "-fallbackfee=0.0002"
  electrs:
    image: registry.gitlab.com/hashbeam/docker/electrs:0.10.9
    depends_on:
      - bitcoind
  proxy:
    image: ghcr.io/rgb-tools/rgb-proxy-server:0.3.0
    ports:
      - 3000:3000
  jupyter:
    image: rgb-lib-python-demo
    build: .
    ports:
      - 8888:8888
    depends_on:
      - electrs
